version: '3.4'

services:
  home:
    image: home
    container_name: home
    build:
      context: .
      dockerfile: Threax.Home/Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/home
        target: /appdata

networks:
  appnet:
    external: true